query currentUser {
  members {
    email
    firstname
    family {
      name
      id
      children {
        birthyear
        firstname
        lastname
        id
      }
    }
    lastname
    isadmin
    id
  }
}