backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
locale: 'es'
collections:
  - name: "pages-ca"
    label: "Pàgines valencià"
    folder: "content/ca/pages"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Contenido"
        name: "body"
        widget: "markdown"
        required: true
    
  - name: "pages-es"
    label: "Páginas castellano"
    folder: "content/es/pages"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Contenido"
        name: "body"
        widget: "markdown"
        required: true

  - name: "blog-ca"
    label: "Blog valencià"
    folder: "content/ca/blog"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - label: "Article en castellà"
        name: "article-es"
        widget: "relation"
        collection: "blog-es"
        search_fields: ["title", "body"]
        display_fields: ["title"]
        value_field: "{{slug}}"
      - label: "Etiquetas"
        name: "tags"
        widget: "list"
        required: false
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: Resumen 164-220
        name: summary
        widget: text
        required: true
        pattern: ['.{164,220}', "Must be within 164 and 220 characters"]
      - label: "Fecha de publicación"
        name: "date"
        widget: "date"
        required: true
      - label: "Fecha de actualización"
        name: "update"
        widget: "date"
        required: false
      - label: "Autor"
        name: "author"
        widget: "string"
        required: true
      - label: "Web del autor"
        name: "authorlink"
        widget: "string"
        required: false
      - label: "Imagen portada"
        name: "thumbnail"
        widget: "image"
        required: true
      - label: "Contenido"
        name: "body"
        widget: "markdown"
        required: true
  - name: "blog-es"
    label: "Blog castellano"
    folder: "content/es/blog"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - label: "Artículo en valenciano"
        name: "article-ca"
        widget: "relation"
        collection: "blog-ca"
        search_fields: ["title", "body"]
        display_fields: ["title"]
        value_field: "{{slug}}"
      - label: "Etiquetas"
        name: "tags"
        widget: "list"
        required: false
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: Resumen 164-220
        name: summary
        widget: text
        required: true
        pattern: ['.{164,220}', "Must be within 164 and 220 characters"]
      - label: "Fecha de publicación"
        name: "date"
        widget: "date"
        required: true
      - label: "Fecha de actualización"
        name: "update"
        widget: "date"
        required: false
      - label: "Autor"
        name: "author"
        widget: "string"
        required: true
      - label: "Web del autor"
        name: "authorlink"
        widget: "string"
        required: false
      - label: "Imagen portada"
        name: "thumbnail"
        widget: "image"
        required: true
      - label: "Contenido"
        name: "body"
        widget: "markdown"
        required: true
